const LOTS=globalThis.LOTS,$=s=>document.querySelector(s);let current=null,drawing=false;
const drawBtn=$("#draw"),status=$("#status"),sticks=$(".sticks");
for(let i=0;i<19;i++){const stick=document.createElement("i");stick.style.setProperty("--i",i);stick.style.setProperty("--delay",`${-(i*.073).toFixed(3)}s`);stick.style.setProperty("--tilt",`${(i%7-3)*2.2}deg`);stick.style.setProperty("--lift",`${7+(i%5)*3}px`);sticks.appendChild(stick)}
function render(lot){current=lot;$("#lot-number").textContent=`第 ${lot.n} 籤`;$("#lot-grade").textContent=lot.grade;$("#lot-title").textContent=`${lot.jiazi}籤`;$("#poem").textContent=lot.poem;$("#zh-explanation").textContent=lot.explanation;$("#story").textContent=`${lot.story}\n\n人生提醒：籤詩提供的是省思方向，宜以真誠、理性與善念面對當下，不必把結果視為不可改變的命運。`;$("#en-translation").textContent=lot.englishTranslation;$("#en-interpretation").textContent=lot.englishInterpretation;$("#draw-screen").hidden=true;$("#result").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
drawBtn.addEventListener("click",()=>{if(drawing)return;drawing=true;drawBtn.classList.remove("reveal");drawBtn.classList.add("shaking");status.textContent="誠心感應中 · 籤枝正在洗牌……";let left=5;const ticker=setInterval(()=>{left--;status.textContent=left?`誠心感應中 · ${left} 秒`:"籤意將現……"},1000);setTimeout(()=>{clearInterval(ticker);drawBtn.classList.remove("shaking");drawBtn.classList.add("reveal");const lot=LOTS[Math.floor(Math.random()*LOTS.length)];$("#chosen-stick").textContent=lot.jiazi;status.textContent=`已抽得第 ${lot.n} 籤 · ${lot.jiazi}籤`;setTimeout(()=>{render(lot);drawing=false},900)},5000)});
$("#again").addEventListener("click",()=>{$("#result").hidden=true;$("#draw-screen").hidden=false;drawBtn.classList.remove("reveal");status.textContent="點擊籤筒開始";window.scrollTo({top:0,behavior:"smooth"})});
function textOf(l){return`六十甲子籤\n第 ${l.n} 籤 · ${l.jiazi}籤 · ${l.grade}\n\n籤詩中文原文\n${l.poem}\n\n中文白話講解\n${l.explanation}\n\nEnglish Translation\n${l.englishTranslation}\n\nEnglish Interpretation\n${l.englishInterpretation}\n\n典故與人生提醒\n${l.story}\n\n僅供靜心自省，不代替醫療、法律或財務建議。`}
$("#copy").addEventListener("click",async e=>{try{await navigator.clipboard.writeText(textOf(current));e.target.textContent="已複製";setTimeout(()=>e.target.textContent="複製文字",1500)}catch{e.target.textContent="請長按文字複製"}});
function wrap(ctx,text,x,y,max,line){let row="";for(const ch of [...text]){if(ctx.measureText(row+ch).width>max){ctx.fillText(row,x,y);row=ch;y+=line}else row+=ch}if(row)ctx.fillText(row,x,y);return y+line}
$("#download").addEventListener("click",()=>{const l=current,c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=1080;c.height=1500;ctx.fillStyle="#fffaf0";ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle="#681715";ctx.lineWidth=14;ctx.strokeRect(28,28,1024,1444);ctx.textAlign="center";ctx.fillStyle="#681715";ctx.font="bold 34px Microsoft JhengHei";ctx.fillText(`第 ${l.n} 籤 · ${l.jiazi}籤 · ${l.grade}`,540,95);ctx.font="bold 52px Microsoft JhengHei";ctx.fillText("六十甲子籤",540,165);ctx.font="36px Microsoft JhengHei";let y=245;for(const line of l.poem.split("\n")){ctx.fillText(line,540,y);y+=58}ctx.textAlign="left";ctx.fillStyle="#38241d";ctx.font="bold 29px Microsoft JhengHei";ctx.fillText("中文白話講解",85,y+30);ctx.font="25px Microsoft JhengHei";y=wrap(ctx,l.explanation,85,y+78,910,42);ctx.fillStyle="#681715";ctx.font="bold 29px Arial";ctx.fillText("English Translation",85,y+18);ctx.fillStyle="#38241d";ctx.font="24px Arial";y=wrap(ctx,l.englishTranslation,85,y+62,910,38);ctx.fillStyle="#681715";ctx.font="bold 29px Arial";ctx.fillText("English Interpretation",85,y+12);ctx.fillStyle="#38241d";ctx.font="24px Arial";wrap(ctx,l.englishInterpretation,85,y+56,910,38);ctx.textAlign="center";ctx.fillStyle="#80684f";ctx.font="20px Microsoft JhengHei";ctx.fillText("僅供靜心自省，不代替醫療、法律或財務建議",540,1432);const a=document.createElement("a");a.download=`六十甲子籤-第${l.n}籤-${l.jiazi}.png`;a.href=c.toDataURL("image/png");a.click()});
