
const $=s=>document.querySelector(s);let lots=[],current=null,busy=false;
fetch("fortunes.json?v=20260812-21").then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(x=>lots=x).catch(()=>{$("#status").textContent="籤詩資料載入失敗，請重新整理。"});
function show(l){current=l;$("#lot-number").textContent=`第 ${l.n} 籤`;$("#lot-grade").textContent=l.grade;$("#lot-title").textContent=`${l.jiazi}籤`;$("#poem").textContent=l.poem;$("#zh-explanation").textContent=l.explanation;$("#story").textContent=`${l.story}\n\n人生提醒：宜守正、審勢、修心行善，不因一時順逆失去本心。`;$("#en-translation").textContent=l.englishTranslation;$("#en-interpretation").textContent=l.englishInterpretation;$("#draw-screen").hidden=true;$("#result").hidden=false;scrollTo({top:0,behavior:"smooth"})}
$("#draw").onclick=()=>{if(busy)return;if(!lots.length){$("#status").textContent="籤詩資料載入中，請稍候再試。";return}busy=true;const lot=lots[Math.floor(Math.random()*lots.length)],box=$("#draw"),status=$("#status");box.classList.add("shaking");status.textContent="誠心感應中 · 5 秒";let n=5;const tick=setInterval(()=>{n--;if(n>0)status.textContent=`誠心感應中 · ${n} 秒`},1000);setTimeout(()=>{clearInterval(tick);box.classList.remove("shaking");$("#chosen-stick").textContent=lot.jiazi;status.textContent=`已抽得第 ${lot.n} 籤 · ${lot.jiazi}籤`;show(lot);busy=false},5000)};
$("#again").onclick=()=>{$("#result").hidden=true;$("#draw-screen").hidden=false;$("#draw").classList.remove("reveal");$("#status").textContent="點擊籤筒開始"};
$("#copy").onclick=async()=>{if(!current)return;await navigator.clipboard.writeText(`第 ${current.n} 籤 · ${current.jiazi}籤\n${current.poem}\n\n${current.explanation}\n\n${current.englishTranslation}\n\n${current.englishInterpretation}`);$("#copy").textContent="已複製"};
$("#download").onclick=()=>{if(!current)return;const a=document.createElement("a"),c=document.createElement("canvas"),x=c.getContext("2d");c.width=900;c.height=1200;x.fillStyle="#fffaf0";x.fillRect(0,0,900,1200);x.fillStyle="#681715";x.textAlign="center";x.font="bold 38px serif";x.fillText(`第 ${current.n} 籤 · ${current.jiazi}籤`,450,80);x.font="30px serif";current.poem.split("\n").forEach((v,i)=>x.fillText(v,450,180+i*55));a.download=`第${current.n}籤-${current.jiazi}.png`;a.href=c.toDataURL();a.click()};

